### ISSUE TITLE
运行不了，缺少文件，不止这一个

### ISSUE THREAD

**Issue by 1796448871** [gamejoye/imjoye#1]
https://github.com/gamejoye/imjoye/blob/3440d8c2b94bb4d7b8391baea1a6d48496f49fb8/entry/src/main/ets/pages/ChatWindow.ets#L11

**Comment by gamejoye** [comment]
在上次push代码库的时候我没有完整的把所有的更改都push上来， 所以导致了这个问题。

该IM项目是前后端分离的， 所以在运行本项目之前需要运行后端并配置mysql服务（配置过程不久后将提供）

具体参考[readme](https://github.com/gamejoye/imjoye/blob/master/README.md)

**Comment by 1796448871** [comment]
谢谢解答，感谢参考^ ^
